DATA_ROOT: "/home/oahmed6/scr4_blangme2/oahmed/khoice_exps/exp7_trial1"
REPO_DIRECTORY: "/home/oahmed6/khoice"
RINDEX_BUILD_DIRECTORY: "/home/oahmed6/r-index_dev/build"
NUM_DATASETS: 3
EXP_TYPE: 7
THRESHOLD: 15
PBSIM_MODEL: "/home/oahmed6/pbsim2/data/R95.model"
KMERS_PER_DATASET: 25000000
NON_KMERS_PER_DATASET: 25000000
NUM_READS_PER_DATASET: 10000
TRIAL_INFO_DIR: "/home/oahmed6/scr4_blangme2/oahmed/khoice_exps/trial_info"


